### PR TITLE
Add new Kapton references to library.yml.

### PR DESCRIPTION
**Pull request by BirgitZatschler**
Hi, 

sorry to bother you again. I did not realize that I also need to add the references to the library.yml. I hope I haven't missed anything else.

Cheers, 
Birgit

### CODE REVIEW

**Comment by polyanskiy** [comment]
Hi Birgit,
thank you for your contribution!
Your data is now included in the database and can be accessed online on refreactiveindex.info
Best regards,
Mikhail

**Comment by BirgitZatschler** [comment]
Hi Mikhail, 
thank you. Would you be able to change my affiliation in database/doc/changelog.txt to "University of Toronto, Canada"? Seems like I forgot to update my profile when I moved.
Cheers, 
Birgit

**Comment by polyanskiy** [comment]
Done!

**Comment by BirgitZatschler** [comment]
Thank you!

**Pull request merged**
