### PR TITLE
added comment about energy conversion to wavelength for Sik data

### PR DESCRIPTION
**Pull request by MK8J**
Fantastic work getting this off the ground and so much information together. 

Please see if these are suitable for entry into your database.

### CODE REVIEW

**Comment by polyanskiy** [comment]
Thanks a lot, looks great! Just give me few days to review it and put online.

**Comment by polyanskiy** [comment]
Hi! I have a question about Daub's data: how did you get the numerical values? Digitizing the figure? If so, the range of the your data seems larger than the range shown on the figure in the original paper...

**Comment by MK8J** [comment]
Good eyes!

I think I got is from a published private communication. I'll check and
provide a reference, though I can't few several hours.

Mattias

On 23 Jun 2017 12:11 PM, "Mikhail Polyanskiy" <notifications@github.com>
wrote:

Hi! I have a question about Daub's data: how did you get the numerical
values? Digitizing the figure? If so, the range of the your data seems
larger than the range shown on the figure in the original paper...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/polyanskiy/refractiveindex.info-database/pull/20#issuecomment-310551381>,
or mute the thread

**Comment by MK8J** [comment]
Hi Mikhail,

Your investigation was with merrit! You have found a mistake in my
documentation, which has been there for several years!

The data was provided Schinke in a private communication and  published in:
Schinke, C., Hinken, D., Schmidt, J., Bothe, K., Brendel, R., 2013.
Modeling the Spectral Luminescence Emission of Silicon Solar Cells and
Wafers. IEEE Journal of Photovoltaics 3, 1038–1052.
doi:10.1109/JPHOTOV.2013.2263985

The data was originally presented in figure 10 of Daub's thesis not his
publication that I had referenced.

E. Daub, “Photolumineszenz von Silizium,” Ph.D. dissertation, Dept.

Phys., University of Karlsruhe, Karlsruhe, Germany, 1995.


Thanks

Mattias

**Comment by polyanskiy** [comment]
Hi Mattias,
your data are now online! Please take a look and let me know if everything is alright:
https://refractiveindex.info/?shelf=main&book=Si&page=Schinke
https://refractiveindex.info/?shelf=main&book=Si&page=Green-2008
https://refractiveindex.info/?shelf=main&book=Si&page=Sik-25C
https://refractiveindex.info/?shelf=main&book=Si&page=Sik-250C
https://refractiveindex.info/?shelf=main&book=Si&page=Sik-500C
https://refractiveindex.info/?shelf=main&book=Si&page=Sik-700C
https://refractiveindex.info/?shelf=main&book=Si&page=Sik-850C
https://refractiveindex.info/?shelf=main&book=Si&page=Daub
Thanks again!
Mikhail

**Comment by MK8J** [comment]
Hey Mikhail,

Everything looks great. Thanks for the efforts!


On the scripts you have attached to the github, I think,
https://github.com/kitchenknif/PyTMM, might not properly take into account
the extinction coefficient. There is an implementation that does here
https://pypi.python.org/pypi/tmm.

Mattias

**Comment by kitchenknif** [comment]
Hi Mattias,
Hmm. 
I wasn't sure if the way I had implemented complex refractive indices in PyTMM was correct, but couldn't think of any quick way of checking... If you have an example that definitely shows incorrect behaviour, I would really appreciate it. 

That being said,
https://github.com/kitchenknif/PyATMM
Handles complex refractive indices correctly, and can also work with anisotropic (uniaxial) materials, but is a bit more complex.

**Comment by MK8J** [comment]
Hey Pavel,

I wouldn't rule at user error yet . See below is my attempt at comparing 3
TMM implementations.

I compared a stack of a-Si [272 nm] and Si [infinite], optical constants
shown below.   So layers without k, I got good agreement between all
models.
Zip below containing everything required.

i did simulations at 0 deg, so polarization doesn't matter.

pyTMM seems to do some where stuff, giving over 100% transmission.

Yeah I has a look at pyATMM, and put it in the to hard basket for now. I'm
only dealing with  isotropic materials.


Mattias
[image: Inline images 1]
[image: Inline images 2]

**Comment by kitchenknif** [comment]
@MK8J @polyanskiy 
Moved the issue with PyTMM to the relevant project https://github.com/kitchenknif/PyTMM/issues/1
Can probably close this one?

Pavel

**Pull request merged**
